### ISSUE TITLE
Not working on JB

### ISSUE THREAD

**Issue by ghost** [Proficient-Apps/MaterializeXposedInstaller#3]
This is not working on Jelly Bean.

**Comment by Proficient-Apps** [comment]
This module is only compatible for Android versions 5.0+
Kitkat and below are not supported.

**Comment by ghost** [comment]
Thanks. It'll be nice if you could add this info on xposed. 😊

**Comment by Freelancer1744** [comment]
спасибо за комментарий, но разве я говорил  о jelly bean. у меня 5,0,2 Linux Kernel realese
